import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "./components/ThemeProvider";
import { ThemeSwitcher } from "./components/ThemeSwitcher";
import { ChakraProvider } from "@chakra-ui/react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-zinc-300 dark:!bg-[#272729] dark:text-white text-[#272729]`}
      >
        <ChakraProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
            <ThemeSwitcher />
          </ThemeProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
